"""empty message

Revision ID: 0ead4bd0dd81
Revises: fd6888369f27
Create Date: 2022-08-15 17:12:13.882498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ead4bd0dd81'
down_revision = 'fd6888369f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'history', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'user_id')
    # ### end Alembic commands ###
