"""empty message

Revision ID: 5f721f6af479
Revises: cfd148a86738
Create Date: 2022-08-04 15:56:38.718363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f721f6af479'
down_revision = 'cfd148a86738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('place_maps_place_id_key', 'place', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('place_maps_place_id_key', 'place', ['maps_place_id'])
    # ### end Alembic commands ###
