"""empty message

Revision ID: fd6888369f27
Revises: 5f721f6af479
Create Date: 2022-08-15 17:08:11.727235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6888369f27'
down_revision = '5f721f6af479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('place_name', sa.String(length=100), nullable=True),
    sa.Column('time_spent', sa.String(length=20), nullable=True),
    sa.Column('mood', sa.String(length=70), nullable=True),
    sa.Column('comments', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
